### ISSUE TITLE
Check for Updates button fails

### ISSUE THREAD

**Issue by meanmedianmoge** [meanmedianmoge/zoia_lib#109]
**Describe the bug**
Check for Updates button in the LS tab fails with error: 
```
Traceback (most recent call last):
  File "/Users/rkm345/PycharmProjects/personal/zoia_lib/zoia_lib/UI/ZOIALibrarian_local.py", line 1107, in run
    count = update.check_for_updates()
  File "/Users/rkm345/PycharmProjects/personal/zoia_lib/zoia_lib/backend/patch_update.py", line 99, in check_for_updates
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rkm345/Library/Application Support/.ZoiaLibraryApp/Folders/Folders.json'
```

**To Reproduce**
1. Go to Local Storage tab
2. Click on Check for Updates
3. Process will fail, no response from UI

**Expected behavior**
Should update patches.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**

**Comment by meanmedianmoge** [comment]
Simple fix - see commit f16a15f.
