### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Poenauta** [meanmedianmoge/zoia_lib#124]
Running on windows 10.Upon install, the app crashes with the following message:

Unhandled exception in script

Failed to execute script 'startup' due to unhandled exception: 'with wrong argument types: PySide2.QtWidgets.QMessageBox.setDetailed Text(AttributeError) Supported signatures: PySide2.QtWidgets.QMessageBox.setDetailed Text(str)

PySide2.QtWidgets.QMessageBox.setDetailed Text' called

Traceback (most recent call last): File "ZOIALibrarian_ps.py", line 60, in metadata_init AttributeError: 'PatchStorage' object has no attribute 'patch_count*

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "startup.py", line 38, in <module>

File "ZOIALibrarian_main.py", line 135, in __init__

File "ZOIALibrarian_ps.py", line 84, in metadata_init

TypeError: 'PySide2.QtWidgets.QMessageBox.setDetailed Text' called with wrong argument types:

Text(AttributeError) PySide2.QtWidgets.QMessageBox.setDetailedText(AttributeError) 

Supported signatures:

PySide2.QtWidgets.QMessageBox.setDetailed Text(str)

**Comment by meanmedianmoge** [comment]
Ready to go for 1.3
