### ISSUE TITLE
Cannot run on Windows 10...

### ISSUE THREAD

**Issue by Scott-Hubbard** [meanmedianmoge/zoia_lib#147]
When I try to run Zoia Patch Manager 1.3 I get the following message....

Unhandled exception in script

Failed to execute script 'startup" due to unhandled exception:
string indices must be integers, not 'str'

Traceback (most recent call last):
  File "startup.py", line 38, in <module>
  File "ZOIALibrarian_main.py", line 413, in __init__
  File "ZOIALibrarian_main.py", line 1122, in sort_and_set
  File "utilities.py", line 71, in sort_metadata
  File "utilities.py", line 71, in <lambda>
TypeError: string indices must be integers, not 'str'_

I'm not real saavy about this stuff, so if someone could help, it would be appreciated!

Thanks

**Comment by daguito81** [comment]
Having the same issue Win 10

**Comment by meanmedianmoge** [comment]
I've identified the issue - will get a fix out asap. Thanks!

**Comment by meanmedianmoge** [comment]
Resolved, set to be in the next bug-fix release. Thanks!
